select
"stat.interfaces.Ethernet1.avg_throughput_pkt_per_s" as throughput,
"setting.ip4-input-no-checksum.size" as ip4_input_no_checksum_size,
"setting.ip6-input.size" as ip6_input_size,
"setting.ip4-lookup.size" as ip4_lookup_size,
"setting.ip4-inacl.size" as ip4_inacl_size,
"setting.nat44-ed-in2out.size" as nat44_ed_in2out_size,
"setting.nat44-ed-in2out-slowpath.size" as nat44_ed_in2out_slowpath_size,

ROUND(AVG("stat.threads.vpp_wk_0.nodes.Ethernet1-output.clocks"),2) as ethernet1_output_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.Ethernet1-output.vectors_per_call"),2) as ethernet1_output_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.Ethernet1-tx.clocks"),2) as ethernet1_tx_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.Ethernet1-tx.vectors_per_call"),2) as ethernet1_tx_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.dpdk-input.clocks"),2) as dpdk_input_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.dpdk-input.vectors_per_call"),2) as dpdk_input_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ethernet-input.clocks"),2) as ethernet_input_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ethernet-input.vectors_per_call"),2) as ethernet_input_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-inacl.clocks"),2) as ip4_inacl_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-inacl.vectors_per_call"),2) as ip4_inacl_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-input-no-checksum.clocks"),2) as ip4_input_no_checksum_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-input-no-checksum.vectors_per_call"),2) as ip4_input_no_checksum_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-lookup.clocks"),2) as ip4_lookup_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-lookup.vectors_per_call"),2) as ip4_lookup_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-rewrite.clocks"),2) as ip4_rewrite_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-rewrite.vectors_per_call"),2) as ip4_rewrite_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-sv-reassembly-feature.clocks"),2) as ip4_sv_reassembly_feature_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-sv-reassembly-feature.vectors_per_call"),2) as ip4_sv_reassembly_feature_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-input.clocks"),2) as ip6_input_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-input.vectors_per_call"),2) as ip6_input_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-lookup.clocks"),2) as ip6_lookup_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-lookup.vectors_per_call"),2) as ip6_lookup_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-rewrite.clocks"),2) as ip6_rewrite_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-rewrite.vectors_per_call"),2) as ip6_rewrite_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.nat-pre-in2out.clocks"),2) as nat_pre_in2out_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.nat-pre-in2out.vectors_per_call"),2) as nat_pre_in2out_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.nat44-ed-in2out.clocks"),2) as nat44_ed_in2out_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.nat44-ed-in2out.vectors_per_call"),2) as nat44_ed_in2out_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.nat44-ed-in2out-slowpath.clocks"),2) as nat44_ed_in2out_slowpath_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.nat44-ed-in2out-slowpath.vectors_per_call"),2) as nat44_ed_in2out_slowpath_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.unix-epoll-input.clocks"),2) as unix_epoll_input_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.unix-epoll-input.vectors_per_call"),2) as unix_epoll_input_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.icmp6-router-solicitation.clocks"),2) as icmp6_router_solicitation_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.icmp6-router-solicitation.vectors_per_call"),2) as icmp6_router_solicitation_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-drop.clocks"),2) as ip6_drop_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-drop.vectors_per_call"),2) as ip6_drop_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-mfib-forward-lookup.clocks"),2) as ip6_mfib_forward_lookup_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-mfib-forward-lookup.vectors_per_call"),2) as ip6_mfib_forward_lookup_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.drop.clocks"),2) as drop_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.drop.vectors_per_call"),2) as drop_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-receive.clocks"),2) as ip6_receive_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-receive.vectors_per_call"),2) as ip6_receive_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-icmp-input.clocks"),2) as ip6_icmp_input_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-icmp-input.vectors_per_call"),2) as ip6_icmp_input_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-replicate.clocks"),2) as ip6_replicate_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-replicate.vectors_per_call"),2) as ip6_replicate_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-mfib-forward-rpf.clocks"),2) as ip6_mfib_forward_rpf_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip6-mfib-forward-rpf.vectors_per_call"),2) as ip6_mfib_forward_rpf_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.error-drop.clocks"),2) as error_drop_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.error-drop.vectors_per_call"),2) as error_drop_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-mfib-forward-lookup.clocks"),2) as ip4_mfib_forward_lookup_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-mfib-forward-lookup.vectors_per_call"),2) as ip4_mfib_forward_lookup_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-drop.clocks"),2) as ip4_drop_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-drop.vectors_per_call"),2) as ip4_drop_vectors_per_call,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-mfib-forward-rpf.clocks"),2) as ip4_mfib_forward_rpf_clocks,
ROUND(AVG("stat.threads.vpp_wk_0.nodes.ip4-mfib-forward-rpf.vectors_per_call"),2) as ip4_mfib_forward_rpf_vectors_per_call

from vpp_exp_data
group by
"stat.interfaces.Ethernet1.avg_throughput_pkt_per_s",
"setting.ip6-input.size",
"setting.ip4-lookup.size",
"setting.ip4-inacl.size",
"setting.nat44-ed-in2out.size",
"setting.nat44-ed-in2out-slowpath.size",
"setting.ip4-input-no-checksum.size"
order by throughput desc;